### PR TITLE
initial Fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
This PR provides initial Fastlane structure for the app. It imports existing summaries from F-Droid, and integrates an updated app description. Also included is an icon (taken from `ActivityLauncherApp/src/main/ic_launcher-web.png` and optimized with `optipng`).

You are welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) to build on this. Recommended additions:

* the `whatsnew/whatsnew-en-GB` for future versions should go to `fastlane/metadata/android/en-US/changelogs/<versionCode>.txt` so F-Droid shows it right next to the app description
* files from `descriptions/*.txt` should be placed into their corresponding languages `full_description.txt` (see `fastlane/metadata/android/en-US/full_description.txt` for an example)
* screenshots should be added to `fastlane/metadata/android/en-US/images/phoneScreenshots/`
* you could also have your featureGraphic added to `fastlane/metadata/android/en-US/images/featureGraphic.png` (or `.jpg`) – I see there is one at PlayStore :wink:

Once this is merged and you are going to tag the next release, please drop a note for us at F-Droid to prepare on our end (we'll need to remove our local descriptions so yours can take over – else ours would override yours).

### CODE REVIEW

**Comment by butzist** [comment]
Thank you for the MR providing an initial Fastlane structure. In order to avoid redundancy in the translations, I would like to integrate it with the translations from [Crowdin](https://crowdin.com/project/activitylauncher), before I merge it.

See the `descriptions/` directory and `update-translations.sh` scripts. These are used to sync the translations from Crowdin for the string resources and for the Play Store listing. Any ideas how to integrate it cleanly?

**Comment by IzzySoft** [comment]
> In order to avoid redundancy in the translations, I would like to integrate it with the translations from Crowdin, before I merge it.

Of course, as you please. I was just starting the PR to provide the structure (as the linked issue showed might be helpful).

And yes, I saw the `description/` directory; I just didn't integrate that for 2 reasons: 1) I didn't want to *move* that as I don't know what I'd break by this, and 2) the last 2/3 of each description there would just duplicate what F-Droid integrates by other means (source code URL, translation URL, etc) and thus would look a bit weird :wink:

For a "clean integration": depends on how you want to handle that. You could simply sync to the corresponding Fastlane directories and, apart from that, keep everything as-is. That would probably work, but as pointed out descriptions at F-Droid would look a bit weird (and the "opt-in for Google Play Beta" would lead to, ahem, some comments). You could of course drop those trailing 2/3 and separate them to their own "strings", and then applying the first to Fastlane and both to the current location, which would be much cleaner.

**Comment by Mrnathanwayne1** [comment]
{
"package": "de.kai_morich.serial_usb_terminal",
"date": " 20211228-122218",
"config": {
"pref_auto_scroll": true,
"pref_baud_rate": "19200",
"pref_break_duration": "100",
"pref_char_delay": "0",
"pref_charset": "UTF-8",
"pref_clear_send": true,
"pref_data_bits": "8",
"pref_font_family": "0",
"pref_font_size": "14",
"pref_keep_screen_on": true,
"pref_line_delay": "0",
"pref_macro_rows": "0",
"pref_parity": "None",
"pref_receive_buffer_size": "10000",
"pref_receive_display_mode": "0",
"pref_receive_newline": "STX/ETX",
"pref_save_directory": "/storage/emulated/0/Android/data/de.kai_morich.serial_usb_terminal/files",
"pref_send_display_mode": "0",
"pref_send_newline": "STX/ETX",
"pref_show_control_lines": true,
"pref_show_send": true,
"pref_show_status": true,
"pref_show_timestamp": true,
"pref_stop_bits": "1",
"pref_timestamp_format": "HH:mm:ss.SSS"
}
}

**Comment by IzzySoft** [comment]
Just wondering if this was forgotten?

**Comment by butzist** [comment]
> Just wondering if this was forgotten?

No, just nobody seems to have time to work on it. Still needs integration with Crowdin and GitHub actions.

**Comment by IzzySoft** [comment]
Ah, the usual problem we all know (lack of time)… hope you don't mind a keep-alive every now and then (I won't ask too often :smile:)

**Comment by IzzySoft** [comment]
Just a note: I'll drop my fork soon, so please merge ASAP.

**Comment by danyroldan7** [comment]
$ bfg --delete-files YOUR-FILE-WITH-SENSITIVE-DATA

**Review by danyroldan7 — CHANGES_REQUESTED** [review]
``$ bfg --delete-files YOUR-FILE-WITH-SENSITIVE-DATA

**Review by danyroldan7 — CHANGES_REQUESTED** [review]
$ bfg --delete-files YOUR-FILE-WITH-SENSITIVE-DATA

**Comment by IzzySoft** [comment]
OK, then I'll remove it now. No idea what those last comments are supposed to mean, though :thinking:

**Comment by butzist** [comment]
Sorry @IzzySoft, appreciate your help with this one. But as mentioned earlier, without the necessary automation, this will just create more maintenance overhead for a project that I (and apparently the rest of the open source community) don't have the time/motivation to handle the most basic feature/bugfix requests.

**Comment by IzzySoft** [comment]
No worries, I don't feel offended. I just don't get the "maintenance overhead", but then I don't know your exact workflow either (you must maintain these things somewhere, and Fastlane is the most wide-spread foundation for that with Android apps).

Should you one day decide to use fastlane, my Cheat Sheet is still linked in the first post, and you can still take a look at the "changes" of this PR to cross-check. So all the best for your project!

**Pull request closed without merging**
