### PR TITLE
Allow uninstall without losing userdata!

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by drogga** [comment]
Can somebody please explain why we needed this, what exactly is the point of it and what's the use case scenario ?, because everytime the app is launched, it checks other app's activities and it doesn't store them because those are a matter of change and are not fixed, like when a new app is installed or old one updated it should and does rechecks them all and it does not create internal DB of the previously available app's activities in order to load faster next time launched, which would be pointless..., keeping them listed, while it's still in the recents (not swiped away - actually closed) is another thing.

**Comment by drogga** [comment]
@upintheairsheep ^

**Comment by drogga** [comment]
@upintheairsheep @butzist ^?

**Comment by upintheairsheep** [comment]
It is mainly for future proofing

**Comment by upintheairsheep** [comment]
> Can somebody please explain why we needed this, what exactly is the point of it and what's the use case scenario ?, because everytime the app is launched, it checks other app's activities and it doesn't store them because those are a matter of change and are not fixed, like when a new app is installed or old one updated it should and does rechecks them all and it does not create internal DB of the previously available app's activities in order to load faster next time launched, which would be pointless..., keeping them listed, while it's still in the recents (not swiped away - actually closed) is another thing.

Mainly for future proofing when settings and caching is added.

**Pull request merged**
