### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by butzist**

### CODE REVIEW

**Review by vaimalaviya1233 — APPROVED** [review]
material component implementation for dark ui in androidx supported platforms

**Review by vaimalaviya1233 — CHANGES_REQUESTED** [review]
material component implementation for dark ui in androidx supported platforms

**Review by vaimalaviya1233 — APPROVED** [review]
Dark mode is completed i have completed updating all files that were chaged to support dark mode in fork i don’t know if this pull request import all of those changes I think it should all files which were updated i see all here. so it's complete. and review it

**Review by vaimalaviya1233 — APPROVED** [review]

**Review by vaimalaviya1233 — APPROVED** [review]

**Review by vaimalaviya1233 — APPROVED** [review]

**Comment by vaimalaviya1233** [comment]
Finally Done there's option which you can choose to use between material or android default theme. That's it 👍.

**Comment by butzist** [comment]
Thank you for the PR @vaimalaviya1233 ,

I will fix the CI in the next weeks and then merge your code. Can you explain how the user would switch between light and dark mode? Or would we not support light mode any more?

**Comment by vaimalaviya1233** [comment]
I have edited layout to change background colors to dark through style attribute so dark theme would support oldest android but if you want I can implement switch that could change between light and dark (but wouldn't be effective against changing themes between light and dark in Android that doesn't support at all like Android 6.0, 7.0 and earlier versions since dark mode of Android introducedin Android 9.0 ) but I can make it work but it will take me 2-4 days if you want I can try that?
And currently it have permanent dark mode so no switch since it's been modified to layout layer.
If you want me to design switch to switch themes between then don't merge the code yet.

**Comment by butzist** [comment]
Ok, so on API version 29 you use DayNight, which uses system default, right? And on older API versions you force dark?

**Comment by vaimalaviya1233** [comment]
Yes on api 29 used daynight but there was no way for older Android to turn to dark mode so that's why I had to modify every layout file to add style attribute that have style="@style/__" which applies styles which have android:background and android:textColor defined in styles.xml
Because I modified layout styles to dark colors api 29's daynight would not come to use there but it did in loding process dialog which was not dark

**Pull request merged**
