### PR TITLE
Revert "disabled orientation (#78)"

### PR DESCRIPTION
**Pull request by drogga**
This reverts commit fb86c38411e1e051ed269bb6cf5c7414cdb29c96.

### CODE REVIEW

**Comment by butzist** [comment]
Hey @drogga, why do we need to revert this commit?

**Comment by vaimalaviya1233** [comment]
Unfortunately commit I did was failing build because I forgot to add activity import in main activity, but @oldherl  fixed it in PR #92 & 93. since its fixed there is no need for this

**Comment by drogga** [comment]
@butzist, @vaimalaviya1233 explained it, it's not needed anymore.
I can only close it, but I prefer if you can please delete it, because I cannot. Thanks.

**Comment by butzist** [comment]
@drogga Doesn't look like I can delete the PR, either

**Pull request closed without merging**
