### PR TITLE
Fix for the status bar

### PR DESCRIPTION
**Pull request by Ismael034**
Hi,

I have made a fix for the issue #102. It turns out that the theme was set to `<style name="AppBaseTheme" parent="android:Theme.DeviceDefault">` so it takes the color palette from the phone. The defaut palette color for Samsung phones is Blue, White and Black. Thus the reason why the status bar was showing a blue color.

For this fix I have created two colors.xml files. Each one set to one theme. I have also removed the styles files as they are not necesary and created a themes.xml one with the `Theme.AppCompat.DayNight` style.

Thanks
image
!

### CODE REVIEW

**Comment by drogga** [comment]
@butzist I ran this, it didn't produce a artifact build (.apk file inside .zip archive container), I think it should've, so I guess it needs to be merged for this, but the question is - which of the 3 merge options should I use (I haven't done this before) ?: 
1) Create
2) Squash
3) Rebase

**Comment by butzist** [comment]
Please never merge before testing...

**Comment by butzist** [comment]
I will test and merge. Will also check if it's possible to produce an
artifact in a PR build.

**Comment by drogga** [comment]
That would be nice (to have artifact for testing before merging), else I would have to create a new branch and build that and if everything is ok to merge it to master, don't worry, I would never merge blandly ;) tho this seems legit...

**Comment by drogga** [comment]
@butzist I also noticed that your Play Store signature key is different than the one used here for the builds, why don't you use the same one, so they can be updated over (Git<>Play, without the need to uninstall first, or you use key rotation ?, which is available since scheme v3 and 9 Pie it seems...

BTW - it would be better if the "Create shortcut" & "Create shortcut as root" context items are moved/reAranged to above "Edit shortcut", this being the last one (as is) and the 2 "Launch" ones being on top...

**Comment by drogga** [comment]
@Ismael034 we have couple of workflow setups already, no need for another one as butzist wrote that he will adjust the PR one to produce artifact, I meant to build one in your for repo, but I now see that is failing, the same as mine, I don't think that I should be approving this (last commitS).

**Comment by Ismael034** [comment]
> @Ismael034 we have couple of workflow setups already, no need for another one as butzist wrote that he will adjust the PR one to produce artifact, I meant to build one in your repo, but I now see that is failing, the same as mine, I don't think that I should be approving this (last commitS).

Yes, noticed that. Sorry. Was making some test and made commits to this issue without noticing

**Comment by drogga** [comment]
can you retract them somehow ?, because it's messy that way, only the theme ones which I approved and ran should stay...

**Comment by Ismael034** [comment]
> can you retract them somehow ?, because it's messy that way, only the theme ones which I approved and ran should stay...
I did a reset so only the theme one are showing now

**Comment by Ismael034** [comment]
I have made a few changes and I think its working. You can now download de debug build when there is a PR

**Comment by drogga** [comment]
Yes, you guessed it right, you don't have a permission to delete the workflows, only the owner and the collaborators can.

The "Debug Build for PR" workflow should auto-generate and use the same "Android Debug" key/signature as before, it shouldn't rely and look for the private one, which, it looks like it forcefully does for the forks too and fails (the .jks is hidden even for me).

Thanks for everything.
I'm leaving this for the owner to decide and approve / merge, as he mentioned that he will take care of this, so I will wait for the adjustments...

@butzist - I hope that you are reading ;)

**Comment by butzist** [comment]
@drogga I'm waiting for @Ismael034  to fix the comments in the PR, because I cannot modify his PR. So, Ismael, I suggest you revert all your changes to the workflows (and I take care of fixing them). Then I'll test and merge your layout chagnes.

**Comment by Ismael034** [comment]
Hi @butzist,
I think I reverted the changes for the workflows. I only left one change which I think it can be useful. If you think that my change to android-pr.yml is not necesary I can revert it.

Thanks

**Comment by drogga** [comment]
@Ismael034 yeah, maybe revert that one for now and keep the code somewhere, so maybe later if it's still needed you can open a new PR, only for the "android-pr.yml", in case the owner doesn't fixes it in the meantime.

Apologies for the trouble, I really appreciate and I understand that you did those for me, because I asked and couldn't test - Thank You ;)

**Comment by drogga** [comment]
@butzist , should some workflows that haven't been approved and ran be deleted ?
Pls also take a look at the other PR...

**Comment by butzist** [comment]
@drogga Will have time on the weekend to looks at the PRs

**Comment by butzist** [comment]
@Ismael034 First of all thank you for the PR and all the effort. I have tested and read through your code and found the following issues:

1. Private activity entries are mostly unreadable with the new color scheme. Tested with Android emulator API versions 19 and 30 with light and dark mode.
2. Some of the new XML files use Windoze line endings. We use Unix in this project.

I will try to integrate a few changes from this PR - but with these issues I cannot fully merge it.

**Comment by Ismael034** [comment]
Hi @butzist
 Sorry about the Windows line-ending. Didn't notice this was a Unix project. I think that the issue with the colors has something to do with the color scheme / theme as it looked good in my phone.

I have also been working in a redesign. See discussion #113. So (In case that becomes the new design of the app) this changes wont be necesary

**Comment by butzist** [comment]
Ok, then I'll revert the custom colors and just keep the switch to AppCompat lib. Works for you?

**Comment by butzist** [comment]
@Ismael034 @drogga I created a Gitter chat for easier exchange: https://gitter.im/ActivityLauncher/community

**Comment by Ismael034** [comment]
@butzist I think so. You can remove the colors.xml files. Try to set text1.setAlpha(1f); and text2.setAlpha(1f);. I think it looks good in the emulator 
image

**Pull request merged**
